### ISSUE TITLE
error in Emacs 24

### ISSUE THREAD

**Issue by gwenhael-le-moine** [fgallina/multi-web-mode#2]
installing multi-web-mode exactly as instructed (for the elisp part) I get the following error when opening a HTML or PHP file:

```
Error in post-command-hook (mweb-post-command-hook): (invalid-function (quote mode))
```

The file is then opened as if multi-web-mode wasn't active (when in fact it is)

**Comment by fgallina** [comment]
My guess is that your config is not matching your installed modes.

Try with this:

```
(require 'multi-web-mode)
(setq mweb-default-major-mode 'html-mode)
(setq mweb-tags '((php-mode "<\\?php\\|<\\? \\|<\\?=" "\\?>")
                  (js-mode "<script +\\(type=\"text/javascript\"\\|language=\"javascript\"\\)[^>]*>" "</script>")
                  (css-mode "<style +type=\"text/css\"[^>]*>" "</style>")))
(setq mweb-filename-extensions '("php" "htm" "html" "ctp" "phtml" "php4" "php5"))
(multi-web-global-mode 1)
```

And be sure you have php-mode properly installed.

**Comment by landtuna** [comment]
I also had this problem, and I fixed it by adding `(eval-when-compile (require 'cl))` to the top of `multi-web-mode.el`. Emacs 24 doesn't like the use of the `case` macro without `cl`.

**Comment by wu-lee** [comment]
I am also seeing this.  I tracked it down to the fact that `mweb-default-major-mode` was not set, because I was impatient to get going.

What might be nice is some usable defaults.  However, failing that a good diagnostic message. I've attempted to supply a patch which gives the latter in pull request #29
