### ISSUE TITLE
how about adding some functions?

### ISSUE THREAD

**Issue by redsnow1992** [fgallina/multi-web-mode#21]
I once used web-mode in web-mode.org. It has some advantages, such as when you set colour in HTML, the colour-character's background will become to the corresponding colour. and it also auto-close the tag in HTML when we press '/'. I'm looking forward these functions.
I also love multi-web-mode, so I want it will be better.

**Comment by Abdillah** [comment]
See `rainbow-mode` to colorize hex.
Moreover, I think that those feature should not be added here, but on specific mode you use..

Maybe take a look here also http://www.emacswiki.org/emacs/HtmlMode, there some list of minor-mode to enhance HTML-mode.
