### ISSUE TITLE
js2-mode doesn't work well as a substitute for js-mode

### ISSUE THREAD

**Issue by slinkp** [fgallina/multi-web-mode#4]
I'm not sure why,  but if i change my config to use js2-mode instead of js-mode,
all highlighting is red and the syntax checking doesn't seem to work.

**Comment by ankhers** [comment]
write a simple javascript file in js2-mode, something along the lines of

``` javascript
var total = 0;
total += 5
document.write(total);
```

Does that still give you bad highlighting?
I don't seem to have any issues when I changed my config to use js2-mode.

I believe the red text means that you have a syntax issue.

**Comment by slinkp** [comment]
js2-mode works fine on the same script if i save it to a separate .js file.

If I take your example and wrap it in script tags: 
    &lt;script type="text/javascript"&gt;
     var total = 0;
     total += 5
     document.write(total);
    &lt;/script&gt;

... the closing tag is highlighted as a syntax error. It looks to me like js2-mode when run under multi-web mode is operating on the whole buffer. I don't know whether that's an obstacle in js2-mode itself, or what.

**Comment by ankhers** [comment]
my guess would be that it is an issue with js2-mode. When I am mixing with an HTML file, I get something a little bit different than what you're describing. I just get no syntax highlighting while in the javascript chunk. I suggest either trying to find the issues and fixing them, or just stick with js-mode.

**Comment by slinkp** [comment]
Sounds like that to me too. Was just hoping you had a clue how to fix it, as I am not really capable in elisp. I'll stick with js-mode. Thanks!
