### ISSUE TITLE
indent-region deletes part of the region

### ISSUE THREAD

**Issue by triccare** [fgallina/multi-web-mode#7]
The situation is as follows:

Issue: indent-region() deletes much of the region. It is clear that there is some point in the file that triggers some failure where, depending on whether mark was placed at the beginning or end of region, will delete from the trigger point to mark.

If not in multi-web-mode, the indent-region works as expected (i.e. nothing is deleted, and the indentation is sometimes wrong because of the mixed mode file, but that is expected).

This is something related to v.24 of Emacs. The same file, sourcing the same startup scripts in v.23 works fine.

The file is a PHP file, and the mode list is (XHMTL yas Multi-Web).

I have removed everything from startup except php-mode (1.5.0) and multi-web-mode with the same result. Except for extra files extensions, the startup is exactly as provided in the standard config.

If I am following things right, it looks like the actual function being called is the built-in sgml-indent-line()

I can provide more info/do more debugging, but at this point I do not know what would be most useful and request guidance.

**Comment by fgallina** [comment]
I have just fixed this in 5b1d495

**Comment by triccare** [comment]
Wow, awesome. will check this out shortly.  Very much thanks.

**Comment by jots** [comment]
I have the same problem with multi-web-mode just installed with elpa.
I disable multi-web-mode and problem does not occur.
have buffer with:

``` html
    <html>
      <head>
        <script>
          function a() {}
       </script>
     </head>
     <body>
     </body>
    </html>
```

select all then indent-region, and everything above script tag is gone.
I set tags like:

``` elisp
    (setq mweb-tags '((php-mode "<\\?php\\|<\\? \\|<\\?=" "\\?>")
                  (js2-mode "<script[^>]*>" "</script>")
                  (css-mode "<style[^>]*>" "</style>")))
```
