### ISSUE TITLE
Improvement to example config

### ISSUE THREAD

**Issue by Lenbok** [fgallina/multi-web-mode#8]
Hi there,

I just downloaded and installed this mode and used the example configuration. On the first html file I loaded, it failed to do any mode switching. After investigation, it turned out that my html file used single quotes rather than double quotes for most of the attributes (e.g. <style type='text/css'>).

It might help new users if you make the example mweb-tags match either type of quote, e.g.

(setq mweb-tags '((php-mode "<\?php\|<\? \|<\?=" "\?>")
                  (js-mode "<script +\\(type=['\"]text/javascript['\"]\\|language=['\"]javascript['\"]\\)[^>]_>" "</script>")
                  (css-mode "<style +type=['\"]text/css['\"][^>]_>" "</style>")))

Cheers.

**Comment by fgallina** [comment]
Fixed in @9460fbc.
