### ISSUE TITLE
package.el

### ISSUE THREAD

**Issue by johnpmayer** [fgallina/multi-web-mode#9]
Is there any interest in getting this uploaded to a public package repository such as ELPA or marmalade?

Alternatively, are you assuming that users have installed el-get? (After I noticed you have a fork of that project)

**Comment by fgallina** [comment]
I just pushed an ELPA friendly header in dc19e15. Let me know if something else is needed from my end.

**Comment by johnpmayer** [comment]
I have uploaded this to marmalade-repo.org

http://marmalade-repo.org/packages/multi-web-mode/0.1
